### ISSUE TITLE
Update to latest ctrulib

### ISSUE THREAD

**Issue by gocario** [mashers/3ds_hb_menu#88]
Adapt the code to match de latest ctrulib would be nice.

**Comment by mashers** [comment]
It's built for the great-refactor branch, which AFAIK is the latest. Unless somebody knows otherwise?

**Comment by ihaveamac** [comment]
technically "great-refactor" as a branch doesn't exist anymore. libctru 1.0.0 was when it was merged. the latest release is 1.1.0 right now.

**Comment by mashers** [comment]
Ok, thanks. Is there any particular reason why it won't build with 1.1.0? Are source changes needed, or just a rebuild with the latest version?

**Comment by gocario** [comment]
I know that the FS_Archive mechanics changed.

**Comment by mashers** [comment]
What do you mean by this? Has some syntax changed requiring adjustments to the source, or just a rebuild with ctrulib 1.1.0?

**Comment by gocario** [comment]
The syntax changed.
I guess the handle is now stored in the archive, and other things.

**Comment by mashers** [comment]
Ok. I'll update my copy of ctrulib when I get a chance, make the necessary changes to the source and push out an update. Thanks for the heads-up - I had no idea such a change had occurred!

**Comment by ihaveamac** [comment]
here's the error I got when building.
```
In file included from /Users/ianburgwin/Desktop/3ds_hb_menu/source/addmenuentry.cpp:10:0:
/Users/ianburgwin/Desktop/3ds_hb_menu/source/filesystem.h:20:8: error: 'FS_archive' does not name a type
 extern FS_archive sdmcArchive;
        ^
/Users/ianburgwin/Desktop/3ds_hb_menu/source/filesystem.h:30:37: error: 'FS_archive' has not been declared
 int loadFile(char* path, void* dst, FS_archive* archive, u64 maxSize);
                                     ^
/Users/ianburgwin/Desktop/3ds_hb_menu/source/filesystem.h:31:29: error: 'FS_archive' has not been declared
 bool fileExists(char* path, FS_archive* archive);
                             ^
make[1]: *** [addmenuentry.o] Error 1
make: *** [build] Error 2
```

**Comment by mashers** [comment]
That's weird. FS_archive is still defined in fs.h, which is included by 3ds.h. So it should work. Did you try to clean first then build? Failing that it might be a cpp thing - maybe an include needs to be wrapped in extern "C"{}. I'll have a look at it my end anyway.

**Comment by ihaveamac** [comment]
I directly tried building after cloning the repository. `make clean` then `make` results in the same thing unless you meant something else

**Comment by mashers** [comment]
No that's what I meant. Hmm, I can't even get ctrulib 1.1.0 to build. I get loads of compiler errors. Did you have to update devKitARM/devKitPro first?

**Comment by ihaveamac** [comment]
I'm using the latest devkitARM which should provide a pre-built libctru.

**Comment by mashers** [comment]
Ahh ok. I'll trash my devKitPro installation and reinstall from scratch.

**Comment by mashers** [comment]
Ok, yup, got the latest devKitPro and ctrulib installed and getting the same FS_archive error here. I'm working on it.

**Comment by JJTapia19** [comment]
This is awesome! Yesterday I was practicing my compiling skills and I gave up trying to compile the hbl mod.  I was mostly getting the error ihaveamac posted. Using older versions of ctrulib helped but I got stuck in another error. I'll try to compile it again once mashers finish working on it.

**Comment by mashers** [comment]
I'm really struggling to resolve this issue. It seems to be something to do with including C headers in C++ implementation files, but I can't for the life of me figure it out. Would really appreciate some help if anyone has time.
